name: aws-codeartifact-mvn-login
description: Login and render settings.xml
branding:
  icon: code
  color: blue
author: Mike Dodge

inputs:
  repo-name:
    description: "Repo name"
    required: true
  repo-domain:
    description: "Repo domain"
    required: false
  account-number:
    description: "AWS acct number"
    required: true
  settings-xml-path:
    description: "folder for m2 settings"
    required: false
    default: "/home/runner/.m2/settings.xml"
  region:
    description: "aws region"
    required: false
    default: "us-east-1"
  duration:
    default: '900'
    description: 'Duration in seconds'
    required: false
outputs:
  token:
    description: 'CodeArtifact Token'
runs:
  using: 'node12'
  main: 'dist/action/index.js'
  post: 'dist/cleanup/index.js'
      
